In [ ]:
# Import packages
import pandas as pd

In [2]:
# Load the schedule data
schedules = pd.read_csv("../data/raw/schedules_2023_2025.csv")

In [3]:
# Preview the data
schedules.head()

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,...,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
0,2023_01_DET_KC,2023,REG,1,2023-09-07,Thursday,20:20,DET,21.0,KC,...,NaN,00-0033106,00-0033873,Jared Goff,Patrick Mahomes,Dan Campbell,Andy Reid,John Hussey,KAN00,GEHA Field at Arrowhead Stadium
1,2023_01_CAR_ATL,2023,REG,1,2023-09-10,Sunday,13:00,CAR,10.0,ATL,...,NaN,00-0039150,00-0038122,Bryce Young,Desmond Ridder,Frank Reich,Arthur Smith,Brad Rogers,ATL97,Mercedes-Benz Stadium
2,2023_01_HOU_BAL,2023,REG,1,2023-09-10,Sunday,13:00,HOU,9.0,BAL,...,NaN,00-0039163,00-0034796,C.J. Stroud,Lamar Jackson,DeMeco Ryans,John Harbaugh,Tra Blake,BAL00,M&T Bank Stadium
3,2023_01_CIN_CLE,2023,REG,1,2023-09-10,Sunday,13:00,CIN,3.0,CLE,...,NaN,00-0036442,00-0033537,Joe Burrow,Deshaun Watson,Zac Taylor,Kevin Stefanski,Clete Blakeman,CLE00,FirstEnergy Stadium
4,2023_01_JAX_IND,2023,REG,1,2023-09-10,Sunday,13:00,JAX,31.0,IND,...,NaN,00-0036971,00-0039164,Trevor Lawrence,Anthony Richardson,Doug Pederson,Shane Steichen,Clay Martin,IND00,Lucas Oil Stadium

In [4]:
# Check dataset size
schedules.shape

(855, 46)

In [5]:
# View all column names
schedules.columns.tolist()

['game_id',
 'season',
 'game_type',
 'week',
 'gameday',
 'weekday',
 'gametime',
 'away_team',
 'away_score',
 'home_team',
 'home_score',
 'location',
 'result',
 'total',
 'overtime',
 'old_game_id',
 'gsis',
 'nfl_detail_id',
 'pfr',
 'pff',
 'espn',
 'ftn',
 'away_rest',
 'home_rest',
 'away_moneyline',
 'home_moneyline',
 'spread_line',
 'away_spread_odds',
 'home_spread_odds',
 'total_line',
 'under_odds',
 'over_odds',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'away_qb_id',
 'home_qb_id',
 'away_qb_name',
 'home_qb_name',
 'away_coach',
 'home_coach',
 'referee',
 'stadium_id',
 'stadium']

In [6]:
# View basic game information
schedules[
    ["season", "week", "home_team", "away_team", "home_score", "away_score"]
].head(10)

   season  week home_team away_team  home_score  away_score
0    2023     1        KC       DET        20.0        21.0
1    2023     1       ATL       CAR        24.0        10.0
2    2023     1       BAL       HOU        25.0         9.0
3    2023     1       CLE       CIN        24.0         3.0
4    2023     1       IND       JAX        21.0        31.0
5    2023     1       MIN        TB        17.0        20.0
6    2023     1        NO       TEN        16.0        15.0
7    2023     1       PIT        SF         7.0        30.0
8    2023     1       WAS       ARI        20.0        16.0
9    2023     1       CHI        GB        20.0        38.0

In [7]:
# Check missing scores
schedules[["season", "week", "home_team", "away_team", "home_score", "away_score"]].isna().sum()

season        0
week          0
home_team     0
away_team     0
home_score    0
away_score    0
dtype: int64

In [9]:
# Keep only completed games
completed_games = schedules.dropna(subset=["home_score", "away_score"]).copy()\
# Then check size
completed_games.shape

(855, 46)

In [10]:
# Create the target variable
completed_games["home_team_won"] = (
    completed_games["home_score"] > completed_games["away_score"]
).astype(int)

# Preview it
completed_games[
    ["season", "week", "home_team", "away_team", "home_score", "away_score", "home_team_won"]
].head(10)

   season  week home_team away_team  home_score  away_score  home_team_won
0    2023     1        KC       DET        20.0        21.0              0
1    2023     1       ATL       CAR        24.0        10.0              1
2    2023     1       BAL       HOU        25.0         9.0              1
3    2023     1       CLE       CIN        24.0         3.0              1
4    2023     1       IND       JAX        21.0        31.0              0
5    2023     1       MIN        TB        17.0        20.0              0
6    2023     1        NO       TEN        16.0        15.0              1
7    2023     1       PIT        SF         7.0        30.0              0
8    2023     1       WAS       ARI        20.0        16.0              1
9    2023     1       CHI        GB        20.0        38.0              0

In [11]:
# Check home win rate
home_win_rate = completed_games["home_team_won"].mean()

home_win_rate

0.5485380116959064

In [13]:
# Create a clean game results dataset
game_results = completed_games[
    [
        "season",
        "week",
        "game_id",
        "gameday",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "home_team_won"
    ]
].copy()

# Preview
game_results.head()

,season,week,game_id,gameday,home_team,away_team,home_score,away_score,home_team_won
0,2023,1,2023_01_DET_KC,2023-09-07,KC,DET,20.0,21.0,0
1,2023,1,2023_01_CAR_ATL,2023-09-10,ATL,CAR,24.0,10.0,1
2,2023,1,2023_01_HOU_BAL,2023-09-10,BAL,HOU,25.0,9.0,1
3,2023,1,2023_01_CIN_CLE,2023-09-10,CLE,CIN,24.0,3.0,1
4,2023,1,2023_01_JAX_IND,2023-09-10,IND,JAX,21.0,31.0,0

In [14]:
# Add point differential
game_results["home_point_diff"] = (
    game_results["home_score"] - game_results["away_score"]
)

# Preview
game_results.head()

,season,week,game_id,gameday,home_team,away_team,home_score,away_score,home_team_won,home_point_diff
0,2023,1,2023_01_DET_KC,2023-09-07,KC,DET,20.0,21.0,0,-1.0
1,2023,1,2023_01_CAR_ATL,2023-09-10,ATL,CAR,24.0,10.0,1,14.0
2,2023,1,2023_01_HOU_BAL,2023-09-10,BAL,HOU,25.0,9.0,1,16.0
3,2023,1,2023_01_CIN_CLE,2023-09-10,CLE,CIN,24.0,3.0,1,21.0
4,2023,1,2023_01_JAX_IND,2023-09-10,IND,JAX,21.0,31.0,0,-10.0

In [15]:
# Save processed dataset
game_results.to_csv("../data/processed/game_results_2023_2025.csv", index=False)

# Confirm it saved
print("Saved processed game results dataset.")
print(game_results.shape)

Saved processed game results dataset.
(855, 10)

In [16]:
# Quick summary
print("Seasons included:", game_results["season"].unique())
print("Total completed games:", len(game_results))
print("Home win rate:", f"{game_results['home_team_won'].mean():.2%}")
print("Average home point differential:", round(game_results["home_point_diff"].mean(), 2))

Seasons included: [2023 2024 2025]
Total completed games: 855
Home win rate: 54.85%
Average home point differential: 2.41

## Summary

In this notebook, I loaded NFL schedule data from the raw data folder, explored the available columns, filtered the dataset to completed games, created a target variable called `home_team_won`, calculated home point differential, and saved a clean processed game results dataset.

The next step is to begin creating pre-game features, such as points scored per game before each matchup, points allowed per game before each matchup, and recent team performance.