# 03 Model Testing

This notebook trains the first baseline model for the NFL forecasting project.

The goal is to use the pre-game features created in the feature engineering notebook to predict whether the home team wins each game.

In [3]:
# Import packages
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
# Load the modeling dataset
modeling_data = pd.read_csv("../data/processed/modeling_dataset_2023_2025.csv")

modeling_data.head()

,season,week,game_id,gameday,home_team,away_team,home_score,away_score,home_team_won,home_point_diff,...,home_win_pct_before,away_games_played_before,away_avg_points_scored_before,away_avg_points_allowed_before,away_avg_point_diff_before,away_win_pct_before,avg_points_scored_diff,avg_points_allowed_diff,avg_point_diff_diff,win_pct_diff
0,2023,1,2023_01_DET_KC,2023-09-07,KC,DET,20.0,21.0,0,-1.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2023,1,2023_01_CAR_ATL,2023-09-10,ATL,CAR,24.0,10.0,1,14.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2023,1,2023_01_HOU_BAL,2023-09-10,BAL,HOU,25.0,9.0,1,16.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2023,1,2023_01_CIN_CLE,2023-09-10,CLE,CIN,24.0,3.0,1,21.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2023,1,2023_01_JAX_IND,2023-09-10,IND,JAX,21.0,31.0,0,-10.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# Check the data
modeling_data.shape
modeling_data.columns.tolist()
modeling_data[["season", "week", "home_team", "away_team", "home_score", "away_score", "home_team_won"]].head()

   season  week home_team away_team  home_score  away_score  home_team_won
0    2023     1        KC       DET        20.0        21.0              0
1    2023     1       ATL       CAR        24.0        10.0              1
2    2023     1       BAL       HOU        25.0         9.0              1
3    2023     1       CLE       CIN        24.0         3.0              1
4    2023     1       IND       JAX        21.0        31.0              0

In [6]:
# Choose model features
features = [
    "avg_points_scored_diff",
    "avg_points_allowed_diff",
    "avg_point_diff_diff",
    "win_pct_diff"
]

target = "home_team_won"

In [7]:
# Create X and y
X = modeling_data[features]
y = modeling_data[target]
X.head()
y.head()

0    0
1    1
2    1
3    1
4    0
Name: home_team_won, dtype: int64

In [8]:
# Check for missing values
X.isna().sum()

avg_points_scored_diff     0
avg_points_allowed_diff    0
avg_point_diff_diff        0
win_pct_diff               0
dtype: int64

In [9]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

Training rows: 641
Testing rows: 214

In [10]:
# Train the logistic regression model
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [11]:
# Make predictions
y_pred = model.predict(X_test)

In [12]:
# Check model accurracy
accuracy = accuracy_score(y_test, y_pred)

print(f"Model accuracy: {accuracy:.2%}")

Model accuracy: 59.35%

In [13]:
# Compare to a simple baseline
home_team_baseline = [1] * len(y_test)

baseline_accuracy = accuracy_score(y_test, home_team_baseline)

print(f"Baseline accuracy if always picking home team: {baseline_accuracy:.2%}")

Baseline accuracy if always picking home team: 54.67%

In [14]:
# Confusion matrix
confusion_matrix(y_test, y_pred)

array([[44, 53],
       [34, 83]], dtype=int64)

The confusion matrix shows how many games the model predicted correctly and incorrectly.

Rows are the actual results.  
Columns are the predicted results.

In [15]:
# Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.56      0.45      0.50        97
           1       0.61      0.71      0.66       117

    accuracy                           0.59       214
   macro avg       0.59      0.58      0.58       214
weighted avg       0.59      0.59      0.59       214

In [16]:
# View model coefficients
coefficients = pd.DataFrame({
    "feature": features,
    "coefficient": model.coef_[0]
})

coefficients.sort_values("coefficient", ascending=False)

                   feature  coefficient
3             win_pct_diff     0.651728
2      avg_point_diff_diff     0.029814
0   avg_points_scored_diff     0.014250
1  avg_points_allowed_diff    -0.015564

In [17]:
# Create predicted probabilities
y_prob = model.predict_proba(X_test)[:, 1]

y_prob[:10]

array([0.5539394 , 0.59212026, 0.59846263, 0.41646985, 0.71016301,
       0.31157616, 0.56564757, 0.46353146, 0.33132803, 0.4537447 ])

In [18]:
# Create a results table
results = modeling_data.loc[X_test.index, [
    "season",
    "week",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "home_team_won"
]].copy()

results["predicted_home_win"] = y_pred
results["home_win_probability"] = y_prob

results.head(10)

,season,week,home_team,away_team,home_score,away_score,home_team_won,predicted_home_win,home_win_probability
13,2023,1,SEA,LA,13.0,30.0,0,1,0.553939
204,2023,14,LAC,DEN,7.0,24.0,0,1,0.592120
722,2025,11,BUF,TB,44.0,32.0,1,1,0.598463
519,2024,16,SEA,MIN,24.0,27.0,0,0,0.416470
667,2025,7,KC,LV,31.0,0.0,1,1,0.710163
663,2025,7,CIN,PIT,33.0,31.0,1,0,0.311576
194,2023,14,ATL,TB,25.0,29.0,0,1,0.565648
555,2024,18,NYJ,MIA,32.0,20.0,1,0,0.463531
803,2025,16,TEN,KC,26.0,9.0,1,0,0.331328
742,2025,12,ARI,JAX,24.0,27.0,0,0,0.453745

In [19]:
# Add predicted winner
results["predicted_winner"] = results.apply(
    lambda row: row["home_team"] if row["predicted_home_win"] == 1 else row["away_team"],
    axis=1
)

results["actual_winner"] = results.apply(
    lambda row: row["home_team"] if row["home_team_won"] == 1 else row["away_team"],
    axis=1
)

results.head(10)

,season,week,home_team,away_team,home_score,away_score,home_team_won,predicted_home_win,home_win_probability,predicted_winner,actual_winner
13,2023,1,SEA,LA,13.0,30.0,0,1,0.553939,SEA,LA
204,2023,14,LAC,DEN,7.0,24.0,0,1,0.592120,LAC,DEN
722,2025,11,BUF,TB,44.0,32.0,1,1,0.598463,BUF,BUF
519,2024,16,SEA,MIN,24.0,27.0,0,0,0.416470,MIN,MIN
667,2025,7,KC,LV,31.0,0.0,1,1,0.710163,KC,KC
663,2025,7,CIN,PIT,33.0,31.0,1,0,0.311576,PIT,CIN
194,2023,14,ATL,TB,25.0,29.0,0,1,0.565648,ATL,TB
555,2024,18,NYJ,MIA,32.0,20.0,1,0,0.463531,MIA,NYJ
803,2025,16,TEN,KC,26.0,9.0,1,0,0.331328,KC,TEN
742,2025,12,ARI,JAX,24.0,27.0,0,0,0.453745,JAX,JAX

In [20]:
# Add correctness column
results["correct_prediction"] = (
    results["predicted_winner"] == results["actual_winner"]
)

results.head(10)

,season,week,home_team,away_team,home_score,away_score,home_team_won,predicted_home_win,home_win_probability,predicted_winner,actual_winner,correct_prediction
13,2023,1,SEA,LA,13.0,30.0,0,1,0.553939,SEA,LA,False
204,2023,14,LAC,DEN,7.0,24.0,0,1,0.592120,LAC,DEN,False
722,2025,11,BUF,TB,44.0,32.0,1,1,0.598463,BUF,BUF,True
519,2024,16,SEA,MIN,24.0,27.0,0,0,0.416470,MIN,MIN,True
667,2025,7,KC,LV,31.0,0.0,1,1,0.710163,KC,KC,True
663,2025,7,CIN,PIT,33.0,31.0,1,0,0.311576,PIT,CIN,False
194,2023,14,ATL,TB,25.0,29.0,0,1,0.565648,ATL,TB,False
555,2024,18,NYJ,MIA,32.0,20.0,1,0,0.463531,MIA,NYJ,False
803,2025,16,TEN,KC,26.0,9.0,1,0,0.331328,KC,TEN,False
742,2025,12,ARI,JAX,24.0,27.0,0,0,0.453745,JAX,JAX,True

In [22]:
# Look at correct predictions
results[results["correct_prediction"] == True].head(10)

,season,week,home_team,away_team,home_score,away_score,home_team_won,predicted_home_win,home_win_probability,predicted_winner,actual_winner,correct_prediction
722,2025,11,BUF,TB,44.0,32.0,1,1,0.598463,BUF,BUF,True
519,2024,16,SEA,MIN,24.0,27.0,0,0,0.416470,MIN,MIN,True
667,2025,7,KC,LV,31.0,0.0,1,1,0.710163,KC,KC,True
742,2025,12,ARI,JAX,24.0,27.0,0,0,0.453745,JAX,JAX,True
112,2023,8,NYG,NYJ,10.0,13.0,0,0,0.390353,NYJ,NYJ,True
512,2024,16,ATL,NYG,34.0,7.0,1,1,0.661841,ATL,ATL,True
446,2024,11,DEN,ATL,38.0,6.0,1,1,0.559343,DEN,DEN,True
649,2025,6,NYJ,DEN,11.0,13.0,0,0,0.292968,DEN,DEN,True
675,2025,7,SF,ATL,20.0,10.0,1,1,0.558793,SF,SF,True
480,2024,14,DET,GB,34.0,31.0,1,1,0.669032,DET,DET,True

In [23]:
# Look at incorrect predictions
results[results["correct_prediction"] == False].head(10)

,season,week,home_team,away_team,home_score,away_score,home_team_won,predicted_home_win,home_win_probability,predicted_winner,actual_winner,correct_prediction
13,2023,1,SEA,LA,13.0,30.0,0,1,0.553939,SEA,LA,False
204,2023,14,LAC,DEN,7.0,24.0,0,1,0.592120,LAC,DEN,False
663,2025,7,CIN,PIT,33.0,31.0,1,0,0.311576,PIT,CIN,False
194,2023,14,ATL,TB,25.0,29.0,0,1,0.565648,ATL,TB,False
555,2024,18,NYJ,MIA,32.0,20.0,1,0,0.463531,MIA,NYJ,False
803,2025,16,TEN,KC,26.0,9.0,1,0,0.331328,KC,TEN,False
365,2024,6,BAL,WAS,30.0,23.0,1,0,0.478993,WAS,BAL,False
458,2024,12,WAS,DAL,26.0,34.0,0,1,0.763639,WAS,DAL,False
82,2023,6,CIN,SEA,17.0,13.0,1,0,0.376348,SEA,CIN,False
668,2025,7,MIN,PHI,22.0,28.0,0,1,0.602394,MIN,PHI,False

In [24]:
# Save test predictions
results.to_csv("../data/predictions/baseline_model_test_predictions.csv", index=False)

print("Saved baseline model test predictions.")
print(results.shape)

Saved baseline model test predictions.
(214, 12)

In [25]:
# Final summary numbers
print("Model accuracy:", f"{accuracy:.2%}")
print("Home-team baseline accuracy:", f"{baseline_accuracy:.2%}")
print("Number of test games:", len(results))
print("Correct predictions:", results["correct_prediction"].sum())
print("Incorrect predictions:", len(results) - results["correct_prediction"].sum())

Model accuracy: 59.35%
Home-team baseline accuracy: 54.67%
Number of test games: 214
Correct predictions: 127
Incorrect predictions: 87

## Summary

In this notebook, I trained the first baseline model for the NFL forecasting project.

The model used logistic regression to predict whether the home team would win. The first set of features included pre-game differences in points scored, points allowed, point differential, and win percentage.

This model is only a starting point. The next steps are to test better features, improve the train-test strategy, and eventually use the model to predict upcoming games.