# 07 EPA Features

This notebook adds Expected Points Added, also called EPA, features to the NFL forecasting model.

The previous best model used basic scoring, win percentage, and recent-form features. This notebook adds play-by-play efficiency features so the model can evaluate how efficient each team has been before each game.

Previous best accuracy: 62.46%

In [1]:
# Import packages
import os
import pandas as pd
import nfl_data_py as nfl

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load play-by-playh data
seasons = list(range(2018, 2026))

pbp = nfl.import_pbp_data(seasons)

pbp.head()

2018 done.
2019 done.
2020 done.
2021 done.
2022 done.
2023 done.
2024 done.
2025 done.
Downcasting floats.

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
0,1.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,None,None,None,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
1,37.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
2,52.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
3,75.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,False,HITCH,ZONE_COVERAGE,COVER_3,NaN,NaN,NaN,NaN,NaN,NaN
4,104.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Check play-by-play columns
pbp.shape
pbp.columns.tolist()

['play_id',
 'game_id',
 'old_game_id_x',
 'home_team',
 'away_team',
 'season_type',
 'week',
 'posteam',
 'posteam_type',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'quarter_seconds_remaining',
 'half_seconds_remaining',
 'game_seconds_remaining',
 'game_half',
 'quarter_end',
 'drive',
 'sp',
 'qtr',
 'down',
 'goal_to_go',
 'time',
 'yrdln',
 'ydstogo',
 'ydsnet',
 'desc',
 'play_type',
 'yards_gained',
 'shotgun',
 'no_huddle',
 'qb_dropback',
 'qb_kneel',
 'qb_spike',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'extra_point_result',
 'two_point_conv_result',
 'home_timeouts_remaining',
 'away_timeouts_remaining',
 'timeout',
 'timeout_team',
 'td_team',
 'td_player_name',
 'td_player_id',
 'posteam_timeouts_remaining',
 'defteam_timeouts_remaining',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'posteam_score_post',
 'defteam_score_post',
 'score_differential_post',
 'no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'vegas_wpa',
 'vegas_home_wpa',
 'home_wp_post',
 'away_wp_post',
 'vegas_wp',
 'vegas_home_wp',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'punt_blocked',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'touchback',
 'interception',
 'punt_inside_twenty',
 'punt_in_endzone',
 'punt_out_of_bounds',
 'punt_downed',
 'punt_fair_catch',
 'kickoff_inside_twenty',
 'kickoff_in_endzone',
 'kickoff_out_of_bounds',
 'kickoff_downed',
 'kickoff_fair_catch',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'own_kickoff_recovery',
 'own_kickoff_recovery_td',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'passer_player_id',
 'passer_player_name',
 'passing_yards',
 'receiver_player_id',
 'receiver_player_name',
 'receiving_yards',
 'rusher_player_id',
 'rusher_player_name',
 'rushing_yards',
 'lateral_receiver_player_id',
 'lateral_receiver_player_name',
 'lateral_receiving_yards',
 'lateral_rusher_player_id',
 'lateral_rusher_player_name',
 'lateral_rushing_yards',
 'lateral_sack_player_id',
 'lateral_sack_player_name',
 'interception_player_id',
 'interception_player_name',
 'lateral_interception_player_id',
 'lateral_interception_player_name',
 'punt_returner_player_id',
 'punt_returner_player_name',
 'lateral_punt_returner_player_id',
 'lateral_punt_returner_player_name',
 'kickoff_returner_player_name',
 'kickoff_returner_player_id',
 'lateral_kickoff_returner_player_id',
 'lateral_kickoff_returner_player_name',
 'punter_player_id',
 'punter_player_name',
 'kicker_player_name',
 'kicker_player_id',
 'own_kickoff_recovery_player_id',
 'own_kickoff_recovery_player_name',
 'blocked_player_id',
 'blocked_player_name',
 'tackle_for_loss_1_player_id',
 'tackle_for_loss_1_player_name',
 'tackle_for_loss_2_player_id',
 'tackle_for_loss_2_player_name',
 'qb_hit_1_player_id',
 'qb_hit_1_player_name',
 'qb_hit_2_player_id',
 'qb_hit_2_player_name',
 'forced_fumble_player_1_team',
 'forced_fumble_player_1_player_id',
 'forced_fumble_player_1_player_name',
 'forced_fumble_player_2_team',
 'forced_fumble_player_2_player_id',
 'forced_fumble_player_2_player_name',
 'solo_tackle_1_team',
 'solo_tackle_2_team',
 'solo_tackle_1_player_id',
 'solo_tackle_2_player_id',
 'solo_tackle_1_player_name',
 'solo_tackle_2_player_name',
 'assist_tackle_1_player_id',
 'assist_tackle_1_player_name',
 'assist_tackle_1_team',
 'assist_tackle_2_player_id',
 'assist_tackle_2_player_name',
 'assist_tackle_2_team',
 'assist_tackle_3_player_id',
 'assist_tackle_3_player_name',
 'assist_tackle_3_team',
 'assist_tackle_4_player_id',
 'assist_tackle_4_player_name',
 'assist_tackle_4_team',
 'tackle_with_assist',
 'tackle_with_assist_1_player_id',
 'tackle_with_assist_1_player_name',
 'tackle_with_assist_1_team',
 'tackle_with_assist_2_player_id',
 'tackle_with_assist_2_player_name',
 'tackle_with_assist_2_team',
 'pass_defense_1_player_id',
 'pass_defense_1_player_name',
 'pass_defense_2_player_id',
 'pass_defense_2_player_name',
 'fumbled_1_team',
 'fumbled_1_player_id',
 'fumbled_1_player_name',
 'fumbled_2_player_id',
 'fumbled_2_player_name',
 'fumbled_2_team',
 'fumble_recovery_1_team',
 'fumble_recovery_1_yards',
 'fumble_recovery_1_player_id',
 'fumble_recovery_1_player_name',
 'fumble_recovery_2_team',
 'fumble_recovery_2_yards',
 'fumble_recovery_2_player_id',
 'fumble_recovery_2_player_name',
 'sack_player_id',
 'sack_player_name',
 'half_sack_1_player_id',
 'half_sack_1_player_name',
 'half_sack_2_player_id',
 'half_sack_2_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_id',
 'penalty_player_name',
 'penalty_yards',
 'replay_or_challenge',
 'replay_or_challenge_result',
 'penalty_type',
 'defensive_two_point_attempt',
 'defensive_two_point_conv',
 'defensive_extra_point_attempt',
 'defensive_extra_point_conv',
 'safety_player_name',
 'safety_player_id',
 'season',
 'cp',
 'cpoe',
 'series',
 'series_success',
 'series_result',
 'order_sequence',
 'start_time',
 'time_of_day',
 'stadium',
 'weather',
 'nfl_api_id',
 'play_clock',
 'play_deleted',
 'play_type_nfl',
 'special_teams_play',
 'st_play_type',
 'end_clock_time',
 'end_yard_line',
 'fixed_drive',
 'fixed_drive_result',
 'drive_real_start_time',
 'drive_play_count',
 'drive_time_of_possession',
 'drive_first_downs',
 'drive_inside20',
 'drive_ended_with_score',
 'drive_quarter_start',
 'drive_quarter_end',
 'drive_yards_penalized',
 'drive_start_transition',
 'drive_end_transition',
 'drive_game_clock_start',
 'drive_game_clock_end',
 'drive_start_yard_line',
 'drive_end_yard_line',
 'drive_play_id_started',
 'drive_play_id_ended',
 'away_score',
 'home_score',
 'location',
 'result',
 'total',
 'spread_line',
 'total_line',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'home_coach',
 'away_coach',
 'stadium_id',
 'game_stadium',
 'aborted_play',
 'success',
 'passer',
 'passer_jersey_number',
 'rusher',
 'rusher_jersey_number',
 'receiver',
 'receiver_jersey_number',
 'pass',
 'rush',
 'first_down',
 'special',
 'play',
 'passer_id',
 'rusher_id',
 'receiver_id',
 'name',
 'jersey_number',
 'id',
 'fantasy_player_name',
 'fantasy_player_id',
 'fantasy',
 'fantasy_id',
 'out_of_bounds',
 'home_opening_kickoff',
 'qb_epa',
 'xyac_epa',
 'xyac_mean_yardage',
 'xyac_median_yardage',
 'xyac_success',
 'xyac_fd',
 'xpass',
 'pass_oe',
 'nflverse_game_id',
 'old_game_id_y',
 'possession_team',
 'offense_formation',
 'offense_personnel',
 'defenders_in_box',
 'defense_personnel',
 'number_of_pass_rushers',
 'players_on_play',
 'offense_players',
 'defense_players',
 'n_offense',
 'n_defense',
 'ngs_air_yards',
 'time_to_throw',
 'was_pressure',
 'route',
 'defense_man_zone_type',
 'defense_coverage_type',
 'offense_names',
 'defense_names',
 'offense_positions',
 'defense_positions',
 'offense_numbers',
 'defense_numbers']

In [4]:
# Keep useful EPA columns
epa_cols = [
    "season",
    "week",
    "game_id",
    "posteam",
    "defteam",
    "play_type",
    "epa"
]

pbp_epa = pbp[epa_cols].copy()

pbp_epa.head()

   season  week          game_id posteam defteam play_type       epa
0    2018     1  2018_01_ATL_PHI    None    None      None -0.000000
1    2018     1  2018_01_ATL_PHI     ATL     PHI   kickoff -0.000000
2    2018     1  2018_01_ATL_PHI     ATL     PHI   no_play -0.773778
3    2018     1  2018_01_ATL_PHI     ATL     PHI      pass  0.850118
4    2018     1  2018_01_ATL_PHI     ATL     PHI       run  1.005722

In [5]:
# Filter to real offensive plays
pbp_epa = pbp_epa.dropna(subset=["posteam", "defteam", "epa"])

pbp_epa = pbp_epa[
    pbp_epa["play_type"].isin(["run", "pass"])
].copy()

pbp_epa.shape

(277516, 7)

In [6]:
# Create weekly offensive EPA
weekly_off_epa = (
    pbp_epa.groupby(["season", "week", "posteam"])
    .agg(
        off_epa_total=("epa", "sum"),
        off_plays=("epa", "count"),
        off_epa_per_play=("epa", "mean")
    )
    .reset_index()
)

weekly_off_epa = weekly_off_epa.rename(columns={"posteam": "team"})

weekly_off_epa.head()

   season  week team  off_epa_total  off_plays  off_epa_per_play
0    2018     1  ARI     -12.141787         51         -0.238074
1    2018     1  ATL     -14.360798         65         -0.220935
2    2018     1  BAL       3.419919         75          0.045599
3    2018     1  BUF     -39.747009         61         -0.651590
4    2018     1  CAR      -2.003919         58         -0.034550

In [7]:
# Create weekly defensive EPA
weekly_def_epa = (
    pbp_epa.groupby(["season", "week", "defteam"])
    .agg(
        def_epa_allowed_total=("epa", "sum"),
        def_plays=("epa", "count"),
        def_epa_allowed_per_play=("epa", "mean")
    )
    .reset_index()
)

weekly_def_epa = weekly_def_epa.rename(columns={"defteam": "team"})

weekly_def_epa.head()

,season,week,team,def_epa_allowed_total,def_plays,def_epa_allowed_per_play
0,2018,1,ARI,12.512707,74,0.169091
1,2018,1,ATL,-5.225558,64,-0.081649
2,2018,1,BAL,-39.747009,61,-0.651590
3,2018,1,BUF,3.419919,75,0.045599
4,2018,1,CAR,-7.703186,57,-0.135144

In [8]:
# Merge offensive and defensive EPA
weekly_epa = weekly_off_epa.merge(
    weekly_def_epa,
    on=["season", "week", "team"],
    how="outer"
)

weekly_epa.head()

,season,week,team,off_epa_total,off_plays,off_epa_per_play,def_epa_allowed_total,def_plays,def_epa_allowed_per_play
0,2018,1,ARI,-12.141787,51,-0.238074,12.512707,74,0.169091
1,2018,1,ATL,-14.360798,65,-0.220935,-5.225558,64,-0.081649
2,2018,1,BAL,3.419919,75,0.045599,-39.747009,61,-0.651590
3,2018,1,BUF,-39.747009,61,-0.651590,3.419919,75,0.045599
4,2018,1,CAR,-2.003919,58,-0.034550,-7.703186,57,-0.135144

In [9]:
# Fill missing EPA values
weekly_epa = weekly_epa.fillna(0)

weekly_epa.head()

,season,week,team,off_epa_total,off_plays,off_epa_per_play,def_epa_allowed_total,def_plays,def_epa_allowed_per_play
0,2018,1,ARI,-12.141787,51,-0.238074,12.512707,74,0.169091
1,2018,1,ATL,-14.360798,65,-0.220935,-5.225558,64,-0.081649
2,2018,1,BAL,3.419919,75,0.045599,-39.747009,61,-0.651590
3,2018,1,BUF,-39.747009,61,-0.651590,3.419919,75,0.045599
4,2018,1,CAR,-2.003919,58,-0.034550,-7.703186,57,-0.135144

In [10]:
# Sort EPA data
weekly_epa = weekly_epa.sort_values(["team", "season", "week"]).reset_index(drop=True)

weekly_epa.head()

,season,week,team,off_epa_total,off_plays,off_epa_per_play,def_epa_allowed_total,def_plays,def_epa_allowed_per_play
0,2018,1,ARI,-12.141787,51,-0.238074,12.512707,74,0.169091
1,2018,2,ARI,-16.746893,43,-0.389463,13.658527,70,0.195122
2,2018,3,ARI,-10.980623,48,-0.228763,-3.970681,69,-0.057546
3,2018,4,ARI,-6.540291,56,-0.116791,1.771260,61,0.029037
4,2018,5,ARI,-6.187947,45,-0.137510,-16.357235,95,-0.172181

In [11]:
# Create EPA totals before each week
weekly_epa["games_with_epa_before"] = (
    weekly_epa.groupby(["team", "season"]).cumcount()
)

weekly_epa["off_epa_total_before"] = (
    weekly_epa.groupby(["team", "season"])["off_epa_total"]
    .transform(lambda x: x.cumsum().shift(1))
)

weekly_epa["off_plays_before"] = (
    weekly_epa.groupby(["team", "season"])["off_plays"]
    .transform(lambda x: x.cumsum().shift(1))
)

weekly_epa["def_epa_allowed_total_before"] = (
    weekly_epa.groupby(["team", "season"])["def_epa_allowed_total"]
    .transform(lambda x: x.cumsum().shift(1))
)

weekly_epa["def_plays_before"] = (
    weekly_epa.groupby(["team", "season"])["def_plays"]
    .transform(lambda x: x.cumsum().shift(1))
)

In [12]:
# Fill missing pre-game EPA totals
epa_before_cols = [
    "off_epa_total_before",
    "off_plays_before",
    "def_epa_allowed_total_before",
    "def_plays_before"
]

weekly_epa[epa_before_cols] = weekly_epa[epa_before_cols].fillna(0)

In [13]:
# Create pre-game EPA/play features
weekly_epa["off_epa_per_play_before"] = 0.0
weekly_epa["def_epa_allowed_per_play_before"] = 0.0

off_mask = weekly_epa["off_plays_before"] > 0
def_mask = weekly_epa["def_plays_before"] > 0

weekly_epa.loc[off_mask, "off_epa_per_play_before"] = (
    weekly_epa.loc[off_mask, "off_epa_total_before"] /
    weekly_epa.loc[off_mask, "off_plays_before"]
)

weekly_epa.loc[def_mask, "def_epa_allowed_per_play_before"] = (
    weekly_epa.loc[def_mask, "def_epa_allowed_total_before"] /
    weekly_epa.loc[def_mask, "def_plays_before"]
)

In [14]:
# Create last 3 week EPA features
weekly_epa["last3_off_epa_per_play"] = (
    weekly_epa.groupby(["team", "season"])["off_epa_per_play"]
    .transform(lambda x: x.shift(1).rolling(3, min_periods=1).mean())
)

weekly_epa["last3_def_epa_allowed_per_play"] = (
    weekly_epa.groupby(["team", "season"])["def_epa_allowed_per_play"]
    .transform(lambda x: x.shift(1).rolling(3, min_periods=1).mean())
)

weekly_epa[
    ["last3_off_epa_per_play", "last3_def_epa_allowed_per_play"]
] = weekly_epa[
    ["last3_off_epa_per_play", "last3_def_epa_allowed_per_play"]
].fillna(0)

In [15]:
# Keep EPA features only
epa_features = weekly_epa[
    [
        "season",
        "week",
        "team",
        "off_epa_per_play_before",
        "def_epa_allowed_per_play_before",
        "last3_off_epa_per_play",
        "last3_def_epa_allowed_per_play"
    ]
].copy()

epa_features.head()

,season,week,team,off_epa_per_play_before,def_epa_allowed_per_play_before,last3_off_epa_per_play,last3_def_epa_allowed_per_play
0,2018,1,ARI,0.000000,0.000000,0.000000,0.000000
1,2018,2,ARI,-0.238074,0.169091,-0.238074,0.169091
2,2018,3,ARI,-0.307326,0.181745,-0.313768,0.182106
3,2018,4,ARI,-0.280770,0.104228,-0.285433,0.102222
4,2018,5,ARI,-0.234392,0.087488,-0.245006,0.055538

In [16]:
# Save EPA features
os.makedirs("../data/processed", exist_ok=True)

epa_features.to_csv("../data/processed/epa_features_2018_2025.csv", index=False)

print("Saved EPA features.")
print(epa_features.shape)

Saved EPA features.
(4454, 7)

In [17]:
# Load expanded modeling dataset
modeling_data = pd.read_csv("../data/processed/modeling_dataset_expanded_2018_2025.csv")

modeling_data.head()

,season,week,game_id,gameday,home_team,away_team,home_score,away_score,home_team_won,home_point_diff,...,away_last3_avg_point_diff,away_last3_win_pct,avg_points_scored_diff,avg_points_allowed_diff,avg_point_diff_diff,win_pct_diff,last3_avg_points_scored_diff,last3_avg_points_allowed_diff,last3_avg_point_diff_diff,last3_win_pct_diff
0,2018,1,2018_01_ATL_PHI,2018-09-06,PHI,ATL,18.0,12.0,1,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018,1,2018_01_BUF_BAL,2018-09-09,BAL,BUF,47.0,3.0,1,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018,1,2018_01_PIT_CLE,2018-09-09,CLE,PIT,21.0,21.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,1,2018_01_CIN_IND,2018-09-09,IND,CIN,23.0,34.0,0,-11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018,1,2018_01_TEN_MIA,2018-09-09,MIA,TEN,27.0,20.0,1,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# Create home EPA features
home_epa = epa_features.rename(
    columns={
        "team": "home_team",
        "off_epa_per_play_before": "home_off_epa_per_play_before",
        "def_epa_allowed_per_play_before": "home_def_epa_allowed_per_play_before",
        "last3_off_epa_per_play": "home_last3_off_epa_per_play",
        "last3_def_epa_allowed_per_play": "home_last3_def_epa_allowed_per_play"
    }
)

In [19]:
# Create away EPA features
away_epa = epa_features.rename(
    columns={
        "team": "away_team",
        "off_epa_per_play_before": "away_off_epa_per_play_before",
        "def_epa_allowed_per_play_before": "away_def_epa_allowed_per_play_before",
        "last3_off_epa_per_play": "away_last3_off_epa_per_play",
        "last3_def_epa_allowed_per_play": "away_last3_def_epa_allowed_per_play"
    }
)

In [21]:
# Merge home EPA features
modeling_data_epa = modeling_data.merge(
    home_epa,
    on=["season", "week", "home_team"],
    how="left"
)

modeling_data_epa.head()

,season,week,game_id,gameday,home_team,away_team,home_score,away_score,home_team_won,home_point_diff,...,avg_point_diff_diff,win_pct_diff,last3_avg_points_scored_diff,last3_avg_points_allowed_diff,last3_avg_point_diff_diff,last3_win_pct_diff,home_off_epa_per_play_before,home_def_epa_allowed_per_play_before,home_last3_off_epa_per_play,home_last3_def_epa_allowed_per_play
0,2018,1,2018_01_ATL_PHI,2018-09-06,PHI,ATL,18.0,12.0,1,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018,1,2018_01_BUF_BAL,2018-09-09,BAL,BUF,47.0,3.0,1,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018,1,2018_01_PIT_CLE,2018-09-09,CLE,PIT,21.0,21.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,1,2018_01_CIN_IND,2018-09-09,IND,CIN,23.0,34.0,0,-11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018,1,2018_01_TEN_MIA,2018-09-09,MIA,TEN,27.0,20.0,1,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
# Merge away EPA features
modeling_data_epa = modeling_data_epa.merge(
    away_epa,
    on=["season", "week", "away_team"],
    how="left"
)

modeling_data_epa.head()

,season,week,game_id,gameday,home_team,away_team,home_score,away_score,home_team_won,home_point_diff,...,last3_avg_point_diff_diff,last3_win_pct_diff,home_off_epa_per_play_before,home_def_epa_allowed_per_play_before,home_last3_off_epa_per_play,home_last3_def_epa_allowed_per_play,away_off_epa_per_play_before,away_def_epa_allowed_per_play_before,away_last3_off_epa_per_play,away_last3_def_epa_allowed_per_play
0,2018,1,2018_01_ATL_PHI,2018-09-06,PHI,ATL,18.0,12.0,1,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018,1,2018_01_BUF_BAL,2018-09-09,BAL,BUF,47.0,3.0,1,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018,1,2018_01_PIT_CLE,2018-09-09,CLE,PIT,21.0,21.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,1,2018_01_CIN_IND,2018-09-09,IND,CIN,23.0,34.0,0,-11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018,1,2018_01_TEN_MIA,2018-09-09,MIA,TEN,27.0,20.0,1,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
# Check missing EPA values
epa_cols_check = [
    "home_off_epa_per_play_before",
    "home_def_epa_allowed_per_play_before",
    "home_last3_off_epa_per_play",
    "home_last3_def_epa_allowed_per_play",
    "away_off_epa_per_play_before",
    "away_def_epa_allowed_per_play_before",
    "away_last3_off_epa_per_play",
    "away_last3_def_epa_allowed_per_play"
]

modeling_data_epa[epa_cols_check].isna().sum()

home_off_epa_per_play_before            16
home_def_epa_allowed_per_play_before    16
home_last3_off_epa_per_play             16
home_last3_def_epa_allowed_per_play     16
away_off_epa_per_play_before            16
away_def_epa_allowed_per_play_before    16
away_last3_off_epa_per_play             16
away_last3_def_epa_allowed_per_play     16
dtype: int64

In [24]:
# Fill missing EPA values
modeling_data_epa[epa_cols_check] = modeling_data_epa[epa_cols_check].fillna(0)

In [25]:
# Create EPA difference features
modeling_data_epa["off_epa_per_play_diff"] = (
    modeling_data_epa["home_off_epa_per_play_before"] -
    modeling_data_epa["away_off_epa_per_play_before"]
)

modeling_data_epa["def_epa_allowed_per_play_diff"] = (
    modeling_data_epa["home_def_epa_allowed_per_play_before"] -
    modeling_data_epa["away_def_epa_allowed_per_play_before"]
)

modeling_data_epa["last3_off_epa_per_play_diff"] = (
    modeling_data_epa["home_last3_off_epa_per_play"] -
    modeling_data_epa["away_last3_off_epa_per_play"]
)

modeling_data_epa["last3_def_epa_allowed_per_play_diff"] = (
    modeling_data_epa["home_last3_def_epa_allowed_per_play"] -
    modeling_data_epa["away_last3_def_epa_allowed_per_play"]
)

In [26]:
# Save an EPA modeling dataset
modeling_data_epa.to_csv(
    "../data/processed/modeling_dataset_epa_2018_2025.csv",
    index=False
)

print("Saved EPA modeling dataset.")
print(modeling_data_epa.shape)

Saved EPA modeling dataset.
(2227, 48)

In [27]:
# Choose model features
features = [
    "avg_points_scored_diff",
    "avg_points_allowed_diff",
    "avg_point_diff_diff",
    "win_pct_diff",
    "last3_avg_points_scored_diff",
    "last3_avg_points_allowed_diff",
    "last3_avg_point_diff_diff",
    "last3_win_pct_diff",
    "off_epa_per_play_diff",
    "def_epa_allowed_per_play_diff",
    "last3_off_epa_per_play_diff",
    "last3_def_epa_allowed_per_play_diff"
]

target = "home_team_won"

In [28]:
# Train on 2018–2024 and test on 2025
train_data = modeling_data_epa[
    modeling_data_epa["season"].between(2018, 2024)
].copy()

test_data = modeling_data_epa[
    modeling_data_epa["season"] == 2025
].copy()

X_train = train_data[features]
y_train = train_data[target]

X_test = test_data[features]
y_test = test_data[target]

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

Training rows: 1942
Testing rows: 285

In [29]:
# Train model
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [30]:
# Predict
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

In [31]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print(f"EPA feature model accuracy: {accuracy:.2%}")
print("Previous best accuracy: 62.46%")

EPA feature model accuracy: 61.40%
Previous best accuracy: 62.46%

In [32]:
# Home-team baseline
home_team_baseline = [1] * len(y_test)

baseline_accuracy = accuracy_score(y_test, home_team_baseline)

print(f"Home-team baseline accuracy: {baseline_accuracy:.2%}")

Home-team baseline accuracy: 53.33%

In [33]:
# Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.61      0.47      0.53       133
           1       0.61      0.74      0.67       152

    accuracy                           0.61       285
   macro avg       0.61      0.60      0.60       285
weighted avg       0.61      0.61      0.61       285

In [34]:
# Coefficents
coefficients = pd.DataFrame({
    "feature": features,
    "coefficient": model.coef_[0]
})

coefficients.sort_values("coefficient", ascending=False)

                                feature  coefficient
8                 off_epa_per_play_diff     1.356964
10          last3_off_epa_per_play_diff     0.514585
7                    last3_win_pct_diff     0.449079
11  last3_def_epa_allowed_per_play_diff     0.072221
0                avg_points_scored_diff     0.016347
2                   avg_point_diff_diff     0.015876
5         last3_avg_points_allowed_diff     0.002549
1               avg_points_allowed_diff     0.000470
4          last3_avg_points_scored_diff    -0.003085
6             last3_avg_point_diff_diff    -0.005633
3                          win_pct_diff    -0.017147
9         def_epa_allowed_per_play_diff    -0.408718

In [35]:
# Create results table
results = test_data[
    [
        "season",
        "week",
        "game_id",
        "gameday",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "home_team_won"
    ]
].copy()

results["predicted_home_win"] = y_pred
results["home_win_probability"] = y_prob

results["predicted_winner"] = results.apply(
    lambda row: row["home_team"] if row["predicted_home_win"] == 1 else row["away_team"],
    axis=1
)

results["actual_winner"] = results.apply(
    lambda row: row["home_team"] if row["home_team_won"] == 1 else row["away_team"],
    axis=1
)

results["correct_prediction"] = (
    results["predicted_winner"] == results["actual_winner"]
)

results.head(10)

,season,week,game_id,gameday,home_team,away_team,home_score,away_score,home_team_won,predicted_home_win,home_win_probability,predicted_winner,actual_winner,correct_prediction
1942,2025,1,2025_01_DAL_PHI,2025-09-04,PHI,DAL,24.0,20.0,1,1,0.54516,PHI,PHI,True
1943,2025,1,2025_01_KC_LAC,2025-09-05,LAC,KC,27.0,21.0,1,1,0.54516,LAC,LAC,True
1944,2025,1,2025_01_TB_ATL,2025-09-07,ATL,TB,20.0,23.0,0,1,0.54516,ATL,TB,False
1945,2025,1,2025_01_CIN_CLE,2025-09-07,CLE,CIN,16.0,17.0,0,1,0.54516,CLE,CIN,False
1946,2025,1,2025_01_MIA_IND,2025-09-07,IND,MIA,33.0,8.0,1,1,0.54516,IND,IND,True
1947,2025,1,2025_01_CAR_JAX,2025-09-07,JAX,CAR,26.0,10.0,1,1,0.54516,JAX,JAX,True
1948,2025,1,2025_01_LV_NE,2025-09-07,NE,LV,13.0,20.0,0,1,0.54516,NE,LV,False
1949,2025,1,2025_01_ARI_NO,2025-09-07,NO,ARI,13.0,20.0,0,1,0.54516,NO,ARI,False
1950,2025,1,2025_01_PIT_NYJ,2025-09-07,NYJ,PIT,32.0,34.0,0,1,0.54516,NYJ,PIT,False
1951,2025,1,2025_01_NYG_WAS,2025-09-07,WAS,NYG,21.0,6.0,1,1,0.54516,WAS,WAS,True

In [36]:
# Accuracy be week
accuracy_by_week = (
    results.groupby("week")["correct_prediction"]
    .mean()
    .reset_index()
)

accuracy_by_week["accuracy_percent"] = (
    accuracy_by_week["correct_prediction"] * 100
)

accuracy_by_week = accuracy_by_week.drop(columns=["correct_prediction"])

accuracy_by_week

    week  accuracy_percent
0      1         56.250000
1      2         75.000000
2      3         50.000000
3      4         56.250000
4      5         50.000000
5      6         53.333333
6      7         73.333333
7      8         69.230769
8      9         50.000000
9     10         78.571429
10    11         80.000000
11    12         71.428571
12    13         75.000000
13    14         57.142857
14    15         56.250000
15    16         43.750000
16    17         62.500000
17    18         56.250000
18    19         50.000000
19    20         75.000000
20    21         50.000000
21    22          0.000000

In [37]:
# Accuracy by confidence
def get_confidence(prob):
    if prob >= 0.65 or prob <= 0.35:
        return "High"
    elif prob >= 0.57 or prob <= 0.43:
        return "Medium"
    else:
        return "Low"

results["confidence"] = results["home_win_probability"].apply(get_confidence)

confidence_accuracy = (
    results.groupby("confidence")["correct_prediction"]
    .agg(["count", "mean"])
    .reset_index()
)

confidence_accuracy["accuracy_percent"] = confidence_accuracy["mean"] * 100

confidence_accuracy = confidence_accuracy.rename(
    columns={"count": "number_of_games"}
)

confidence_accuracy = confidence_accuracy.drop(columns=["mean"])

confidence_accuracy

  confidence  number_of_games  accuracy_percent
0       High               87         71.264368
1        Low              115         56.521739
2     Medium               83         57.831325

In [38]:
# Save EPA predictions
os.makedirs("../data/predictions", exist_ok=True)

results.to_csv(
    "../data/predictions/epa_model_test_predictions.csv",
    index=False
)

print("Saved EPA model test predictions.")
print(results.shape)

Saved EPA model test predictions.
(285, 15)

In [39]:
# Final summary numbers
print("EPA feature model accuracy:", f"{accuracy:.2%}")
print("Previous best accuracy: 62.46%")
print("Home-team baseline accuracy:", f"{baseline_accuracy:.2%}")
print("Number of test games:", len(results))
print("Correct predictions:", results["correct_prediction"].sum())
print("Incorrect predictions:", len(results) - results["correct_prediction"].sum())

EPA feature model accuracy: 61.40%
Previous best accuracy: 62.46%
Home-team baseline accuracy: 53.33%
Number of test games: 285
Correct predictions: 175
Incorrect predictions: 110

## Summary

In this notebook, I added EPA/play features to the NFL forecasting model.

EPA features are useful because they measure play-level efficiency instead of only using final scores or win percentage. The model now includes offensive EPA/play, defensive EPA allowed/play, and last-3-game EPA features.

The model trained on 2018–2024 and tested on 2025, using the same realistic season-based evaluation setup as the previous notebooks.

The next step is to compare this EPA model accuracy to the previous best accuracy of 62.46%.